import turtle
turtle. showturtle()
turtle. penup()
turtle. goto(-100,-50)
turtle. pendown()
turtle. circle(45)
turtle. penup()
turtle. goto(0,-50)
turtle. pendown()
turtle. circle(45)
turtle. penup()
turtle. goto(110, -50)
turtle. pendown()
turtle. circle(45)
turtle. penup()
turtle. goto(-55, -100)
turtle. pendown()
turtle. circle(45)
turtle. penup()
turtle. goto(55,-100)
turtle. pendown()
turtle. circle(45)